version: '3'

services:
  app:
    image: node:21
    container_name: node_app
    restart: unless-stopped
    volumes:
      - .:/app
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"